### ISSUE TITLE
[Feature Request] Requesting Software

### ISSUE THREAD

**Issue by gatesyp** [stohio/software-lab#1]
Implement software requests. 

1. User tries to download software from our platform
2. Platform responds that the software does not exist
3. User requests the software to be installed (maybe give us a URL?) 
4. We download the software, register it to our platform
5. Now anyone can download the software at fast speeds

**Comment by csinko** [comment]
The plan is to add some sort  of form capabilities where users can both request software and give feedback.  In addition, users will be directed to the feedback form upon downloading.

**Comment by csinko** [comment]
Closing due to duplicate issue #32 .  Please refer to #32 for progress on this feature.
