### ISSUE TITLE
[Feature Request] BitTorrent vs HTTP optimization

### ISSUE THREAD

**Issue by gatesyp** [stohio/software-lab#2]
Find the point where BitTorrent outperforms using http method. 

Then, automatically switch to using BitTorrent protocol in order to maintain extremely high download speeds

**Comment by csinko** [comment]
Upon further thinking, implementing a BitTorrent protocol has a lot of advantages.  The main one being if a node becomes slow, crashes, or becomes disconnected from the network, downloading can automatically transfer to another node without interruption. 

In addition, in situations where only WiFi can be used to host nodes, BitTorrent could realistically yield better download speeds.

While the speed differences may be negligible in other cases, I do not see any cons to moving towards a Bit / Web Torrent Method, but hash checking and more dynamic software file management should be implemented first before doing so.

**Comment by csinko** [comment]
Closing due to duplicate with issue #26.  If you would like to follow progress, please refer to #26.
